# Generated by Django 5.1.3 on 2025-10-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("source_text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("flowchart", "flowchart"),
                            ("sequence", "sequence"),
                            ("state", "state"),
                            ("er", "erDiagram"),
                            ("class", "classDiagram"),
                            ("journey", "journey"),
                            ("gantt", "gantt"),
                            ("timeline", "timeline"),
                            ("pie", "pie"),
                            ("mindmap", "mindmap"),
                            ("gitGraph", "gitGraph"),
                            ("quadrant", "quadrantChart"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "model_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "language",
                    models.CharField(db_index=True, default="ru", max_length=8),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagrams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="DiagramRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="mermind.diagram",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
